---
apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  type: NodePort
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 8020
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
spec:
  selector:
    matchLabels:
      app: graphql
  replicas: 1
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: dquyen2806/graphql
          ports:
            - containerPort: 8020
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8025
            initialDelaySeconds: 30
            timeoutSeconds: 1